version: '2'

services:
  poll-website-php:
    build: docker/php
    working_dir: /app
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini.dist
      - .:/app
    networks:
      - poll-website-net
    command: bash -c "cp /usr/local/etc/php/php.ini.dist /usr/local/etc/php/php.ini && echo \"xdebug.remote_host=`/sbin/ip route|awk '/default/ { print $$3 }'`\" >> /usr/local/etc/php/php.ini && php-fpm"

  poll-website-web:
    image: nginx
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - poll-website-net

  poll-website-db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - poll-website-net

  poll-website-beanstalkd:
    image: schickling/beanstalkd

  poll-website-node:
    image: node:latest
    entrypoint:
      - /app/docker/bin/node-startup.sh
    working_dir: /app
    ports:
      - "3003:3000"
    volumes:
      - ./:/app
    networks:
      - poll-website-net

networks:
  poll-website-net:
